name: CI - Cypress + Postman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Instalar dependências do Cypress
        run: sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libnotify-dev \
          libgconf-2-4 libnss3 libxss1 libasound2 xvfb

      - name: Subir API e rodar testes Postman + Newman
        run: npm run test:api

      - name: Rodar testes do Cypress
        run: npm run test:cypress
