name: CI - Cypress + Postman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Instalar Cypress globalmente
        run: npm install -g cypress

      - name: Instalar Newman e reporter htmlextra globalmente
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Instalar dependências do sistema para Cypress
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-0 \
            libnotify-dev \
            libnss3 \
            libxss1 \
            xvfb

      # Subindo API em background
      - name: Subir API em background
        run: npm run start:api &

      # Esperar API subir antes de rodar testes Postman
      - name: Esperar API subir
        run: sleep 3

      # Rodar testes Postman com Newman
      - name: Rodar testes Postman + Newman
        run: npm run postman:test

      # Rodar testes Cypress
      - name: Rodar testes do Cypress
        run: npm run test:cypress
