name: CI - Cypress + Postman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências do projeto
        run: npm install

      - name: Instalar dependências do sistema para Cypress
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-0 \
            libnotify-dev \
            libnss3 \
            libxss1 \
            xvfb

      - name: Subir API em background
        run: npm run start:api &

      - name: Esperar API subir
        run: sleep 3

      - name: Rodar testes Postman + Newman
        run: npm run postman:test

      - name: Salvar relatório HTML do Newman
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: postman/reports/report.html

      - name: Rodar testes Cypress
        run: npm run cy:run

      - name: Mesclar relatórios Mochawesome JSON
        run: npx mochawesome-merge cypress/reports/*.json > cypress/reports/output.json

      - name: Gerar relatório Mochawesome HTML
        run: npx marge cypress/reports/output.json -f report -o cypress/reports/html

      - name: Salvar relatório do Cypress (Mochawesome)
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/html/report.html
